name: fluter_mvvm_bbs
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.1.2 <4.0.0'
dependencies:
  cloud_firestore: ^4.9.1
  collection: ^1.17.2
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  flutter:
    sdk: flutter
  provider: ^6.0.5
dev_dependencies:
  clock: ^1.1.1
  fake_cloud_firestore: ^2.4.1+1
  firebase_auth_mocks: ^0.12.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.24.0+1
flutter:
  uses-material-design: true