// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoC_a2HbQsFQavzK9wf3GkImV_TcEEyks',
    appId: '1:908960925000:web:96d42237c5348a78dedf7d',
    messagingSenderId: '908960925000',
    projectId: 'flutter-mvvm-bbs-34257',
    authDomain: 'flutter-mvvm-bbs-34257.firebaseapp.com',
    storageBucket: 'flutter-mvvm-bbs-34257.appspot.com',
    measurementId: 'G-CM7F16JNR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbdsXSKxVcBlksXUHt_uem7E9l97VJrRM',
    appId: '1:908960925000:android:8b94ad305f3aa5cadedf7d',
    messagingSenderId: '908960925000',
    projectId: 'flutter-mvvm-bbs-34257',
    storageBucket: 'flutter-mvvm-bbs-34257.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1M88rLELDhl0HLsDxwyNAOmm-qveIgFc',
    appId: '1:908960925000:ios:64facc204d78f112dedf7d',
    messagingSenderId: '908960925000',
    projectId: 'flutter-mvvm-bbs-34257',
    storageBucket: 'flutter-mvvm-bbs-34257.appspot.com',
    iosBundleId: 'com.example.flutterMvvmSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1M88rLELDhl0HLsDxwyNAOmm-qveIgFc',
    appId: '1:908960925000:ios:0575182b8ce3dc87dedf7d',
    messagingSenderId: '908960925000',
    projectId: 'flutter-mvvm-bbs-34257',
    storageBucket: 'flutter-mvvm-bbs-34257.appspot.com',
    iosBundleId: 'com.example.flutterMvvmSample.RunnerTests',
  );
}
